[package]
name = "rusty_neural_net"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
csv = "1.3.1"
linfa = "0.7.1"
linfa-datasets = "0.7.1"
linfa-logistic = "0.7.1"
ndarray = "0.15.6"
rand = "0.9.1"
